package za.co.fnb.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2020-01-31T15:11:48.388+02:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "CalculatorFacadeService", 
                  wsdlLocation = "file:/home/f5074118/Documents/Personal_Development_ws/FNB_DEMO_ws/wss4jdemo-client/src/main/resources/calculator-service.wsdl",
                  targetNamespace = "http://ws.fnb.co.za/") 
public class CalculatorFacadeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.fnb.co.za/", "CalculatorFacadeService");
    public final static QName CalculatorServicePort = new QName("http://ws.fnb.co.za/", "CalculatorServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/f5074118/Documents/Personal_Development_ws/FNB_DEMO_ws/wss4jdemo-client/src/main/resources/calculator-service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculatorFacadeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/f5074118/Documents/Personal_Development_ws/FNB_DEMO_ws/wss4jdemo-client/src/main/resources/calculator-service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculatorFacadeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculatorFacadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorFacadeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CalculatorFacadeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculatorFacadeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculatorFacadeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServicePort")
    public CalculatorService getCalculatorServicePort() {
        return super.getPort(CalculatorServicePort, CalculatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServicePort")
    public CalculatorService getCalculatorServicePort(WebServiceFeature... features) {
        return super.getPort(CalculatorServicePort, CalculatorService.class, features);
    }

}
